import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` (v8's html reporter). Gitignored,
    // but this list replaces eslint's defaults rather than extending them, so
    // without it a local coverage run makes `npm run lint` fail on vendored
    // report scripts.
    "coverage/**",
  ]),
]);

export default eslintConfig;
